/* ImagepopUp JS,  Version: 1.3.1 | http://intomedia.hu, https://github.com/vmarci21/PhotoPopUp */
var imagepopup={
  option:{imageloadingerror_title:"Loading errors",imageloadingerror_text:"Failed to load the picture :(",close_element:'<span class="icon-close"></span>',open_element:'<span class="icon-link"></span>',next_element:'<span class="icon-next"></span>',prev_element:'<span class="icon-prev"></span>',enabled_keyboard_control:true,enabled_touch_control:true},
  ,firstimage:!0,imageherei:0,wherediv:1,gallerye:"",hasnext:!1,hasprev:!1,opened:!1,events_open:[],events_close:[],events_buttonclick:[],new_button:[],
addevent:function(a,b){"onopen"==a?this.events_open.push(b):"onclose"==a?this.events_close.push(b):"onbuttonclick"==a&&this.events_buttonclick.push(b)},newgallery:function(a){if(0<document.getElementsByClassName(a).length)for(var b=document.getElementsByClassName(a),d=0;d<b.length;d++)b[d].addEventListener("click",function(){void 0==this.dataset.bigsrc?imagepopup.showimage(this.src,this.title,a):imagepopup.showimage(this.dataset.bigsrc,this.title,a)})},addbutton:function(a,b){this.new_button.push([a,
b])},buttonclick_run:function(a){this.new_button[a][1]()},showimage:function(a,b,d,c){document.getElementById("imagepopup_prev").innerHTML=imagepopup.option.prev_element;document.getElementById("imagepopup_next").innerHTML=imagepopup.option.next_element;void 0==b&&(b="");document.getElementById("imagepopup_fixer").style.display="none";this.opened=!0;var f="",e=1,g=2;if(void 0==c||""==c||null==c)c=0;this.firstimage&&(window.addEventListener("resize",function(){imagepopup.resizeimage()}),imagepopup.option.enabled_touch_control&&
imagepopup.mobiledrag(),imagepopup.option.enabled_keyboard_control&&imagepopup.keyboard_view(),this.firstimage=!1);if(void 0!=d)for(this.gallerye=d,d=document.getElementsByClassName(d);c<d.length;c++)if(d[c].dataset.bigsrc==a||d[c].src==a)this.imageherei=c,0==this.imageherei%2?(e=1,g=2):(e=2,g=1),0<c?(this.hasprev=!0,document.getElementById("imagepopup_prev").className="active"):(this.hasprev=!1,document.getElementById("imagepopup_prev").className=""),d.length>c+1?(document.getElementById("imagepopup_next").className=
"active",f=void 0!=d[c+1].dataset.bigsrc?d[c+1].dataset.bigsrc:d[c+1].src,this.hasnext=!0):(this.hasnext=!1,document.getElementById("imagepopup_next").className=""),c=d.length;document.getElementById("imagepopup").style.display="block";document.getElementById("imagepopup_load").className="active";setTimeout(function(){document.getElementById("imagepopup").className="active"},30);c=new Image;c.onerror=function(){document.getElementById("imagepopup_load").className="";imagepopup.showtext(imagepopup.option.imageloadingerror_title,
imagepopup.option.imageloadingerror_text)};c.onload=function(){imagepopup.wherediv=e;document.getElementById("imagepopup_load").className="";document.getElementById("imagepopup_image"+g).className="";document.getElementById("imagepopup_image"+e).className="active";document.getElementById("imagepopup_image"+e).innerHTML='<img id="nagy_kep'+e+'" src="'+a+'">';imagepopup.resizeimage();document.getElementById("imagepopup_panel").innerHTML='<a href="'+a+'" target="_blank">'+imagepopup.option.open_element+
'</a> <a href="javascript://" onclick="imagepopup.hideimage();" class="close">'+imagepopup.option.close_element+"</a>";for(var c=0;c<imagepopup.new_button.length;c++)document.getElementById("imagepopup_panel").innerHTML+=' <a href="javascript://" onclick="imagepopup.buttonclick_run('+c+');">'+imagepopup.new_button[c][0]+"</a> ";document.getElementById("imagepopup_text").innerHTML=b;""!=f&&((new Image).src=f);for(c=0;c<imagepopup.events_open.length;c++)imagepopup.events_open[c](a,b)};c.src=a},showtext:function(a,
b){document.getElementById("imagepopup_fixer").style.display="none";document.getElementById("imagepopup").style.display="block";document.getElementById("imagepopup_image1").innerHTML='<div id="window"><h3 class="title">'+a+"</h3><p>"+b+"</p></div>";document.getElementById("imagepopup_panel").innerHTML='<a href="javascript://" onclick="imagepopup.hideimage();" class="close">x</a>';setTimeout(function(){document.getElementById("imagepopup").className="active";document.getElementById("imagepopup").className=
"active";document.getElementById("imagepopup_image1").className="active";document.getElementById("imagepopup_image2").className=""},30)},next:function(){for(var a=document.getElementsByClassName(this.gallerye),b=void 0!=a[this.imageherei+1].dataset.bigsrc?a[this.imageherei+1].dataset.bigsrc:a[this.imageherei+1].src,d=0;d<imagepopup.events_buttonclick.length;d++)imagepopup.events_buttonclick[d]("next");this.showimage(b,a[this.imageherei+1].title,this.gallerye,this.imageherei)},prev:function(){for(var a=
document.getElementsByClassName(this.gallerye),b=void 0!=a[this.imageherei-1].dataset.bigsrc?a[this.imageherei-1].dataset.bigsrc:a[this.imageherei-1].src,d=0;d<imagepopup.events_buttonclick.length;d++)imagepopup.events_buttonclick[d]("prev");this.showimage(b,a[this.imageherei-1].title,this.gallerye,this.imageherei-1)},hideimage2:function(a){"imagepopup"!=a.target.id&&"imagepopup_image1"!=a.target.id&&"imagepopup_image2"!=a.target.id||this.hideimage()},hideimage:function(){this.opened=!1;document.getElementById("imagepopup").className=
"";setTimeout(function(){document.getElementById("imagepopup").style.display="none";document.getElementById("imagepopup_text").innerHTML="";document.getElementById("imagepopup_image1").innerHTML="";document.getElementById("imagepopup_image2").innerHTML="";document.getElementById("imagepopup_image1").className="";document.getElementById("imagepopup_image2").className="";document.getElementById("imagepopup_prev").className="";document.getElementById("imagepopup_next").className="";document.getElementById("imagepopup_fixer").style.display=
"block"},400);for(var a=0;a<imagepopup.events_close.length;a++)imagepopup.events_close[a]()},resizeimage:function(){if(document.getElementById("nagy_kep"+this.wherediv)){var a=document.getElementById("imagepopup").offsetWidth,b=document.getElementById("imagepopup").offsetHeight,b=b-50;document.getElementById("nagy_kep"+this.wherediv).style.maxWidth=a+"px";document.getElementById("nagy_kep"+this.wherediv).style.maxHeight=b+"px";var a=document.getElementById("nagy_kep"+this.wherediv).offsetWidth,a=
a-20,d=document.getElementById("nagy_kep"+this.wherediv).offsetHeight,b=(b-d)/2;6>b&&(b=4);document.getElementById("nagy_kep"+this.wherediv).style.marginTop=b+"px";600<a?(document.getElementById("imagepopup_text").style.width=a+"px",document.getElementById("imagepopup_text").className="kepben",b=d+b+5,document.getElementById("imagepopup_text").style.top=b+"px"):(document.getElementById("imagepopup_text").style.width="",document.getElementById("imagepopup_text").style.top="",document.getElementById("imagepopup_text").className=
"")}},keyboard_view:function(){window.addEventListener("keyup",function(a){imagepopup.opened&&(a="which"in a?a.which:a.keyCode,37==a&&imagepopup.hasprev?imagepopup.prev():39==a&&imagepopup.hasnext?imagepopup.next():27==a&&imagepopup.hideimage())})},mobiledrag:function(){function a(a,b){startx=a;starty=b;ennyit2=ennyit=0;starttop=document.getElementById("nagy_kep"+imagepopup.wherediv).style.marginTop;starttop=starttop.replace("px","")}function b(a,b,d){ennyit=a-startx;ennyit2=starty-b;Math.abs(ennyit)>
Math.abs(ennyit2)?document.getElementById("nagy_kep"+imagepopup.wherediv).style.marginLeft=ennyit+"px":(a=starttop-ennyit2,document.getElementById("nagy_kep"+imagepopup.wherediv).style.marginTop=a+"px");d.preventDefault()}function d(){var a="0px";Math.abs(ennyit)>Math.abs(ennyit2)?(120<ennyit&&imagepopup.hasprev?a="100%":-120>ennyit&&imagepopup.hasnext&&(a="-200%"),document.getElementById("nagy_kep"+imagepopup.wherediv).className="touch",document.getElementById("nagy_kep"+imagepopup.wherediv).style.marginLeft=
a,120<ennyit&&imagepopup.hasprev?imagepopup.prev():-120>ennyit&&imagepopup.hasnext&&imagepopup.next()):100<ennyit2||-100>ennyit2?imagepopup.hideimage():(a=starttop+"px",document.getElementById("nagy_kep"+imagepopup.wherediv).className="touch",document.getElementById("nagy_kep"+imagepopup.wherediv).style.marginTop=a);setTimeout(function(){document.getElementById("nagy_kep"+imagepopup.wherediv).className=""},200)}ennyit2=starttop=ennyit=starty=startx=0;window.PointerEvent&&"undefined"==typeof document.documentElement.ontouchstart?
navigator.maxTouchPoints&&1<navigator.maxTouchPoints&&(window.addEventListener("pointerdown",function(c){a(c.clientX,c.clientY)},!1),window.addEventListener("pointermove",function(a){b(a.clientX,a.clientY,a)},!1),window.addEventListener("pointerup",function(a){d()},!1)):(document.getElementById("imagepopup").addEventListener("touchstart",function(c){c=c.targetTouches[0];a(c.pageX,c.pageY)},!1),document.getElementById("imagepopup").addEventListener("touchmove",function(a){var d=a.targetTouches[0];
b(d.pageX,d.pageY,a)},!1),document.getElementById("imagepopup").addEventListener("touchend",function(a){d()},!1))},hideview:function(a){a=document.getElementById(a);a.style.opacity="1"==a.style.opacity?"0":"1"}};
