/* ImagepopUp JS,  Version: 1.1 | http://intomedia.hu, https://github.com/vmarci21/PhotoPopUp */
var imagepopup={firstimage:!0,imageherei:0,wherediv:1,gallerye:"",hasnext:!1,hasprev:!1,opened:!1,showimage:function(a,d,c,b){document.getElementById("imagepopup_fixer").style.display="none";this.opened=!0;var f="",e=1,g=2;if(void 0==b||""==b||null==b)b=0;this.firstimage&&(window.addEventListener("resize",function(){imagepopup.resizeimage()}),imagepopup.mobiledrag(),imagepopup.keyboard_view(),this.firstimage=!1);if(void 0!=c)for(this.gallerye=c,c=document.getElementsByClassName(c);b<c.length;b++)if(c[b].dataset.bigsrc==
a||c[b].src==a)this.imageherei=b,0==this.imageherei%2?(e=1,g=2):(e=2,g=1),0<b?(this.hasprev=!0,document.getElementById("imagepopup_prev").className="active"):(this.hasprev=!1,document.getElementById("imagepopup_prev").className=""),c.length>b+1?(document.getElementById("imagepopup_next").className="active",f=void 0!=c[b].dataset.bigsrc?c[b+1].dataset.bigsrc:c[b+1].src,this.hasnext=!0):(this.hasnext=!1,document.getElementById("imagepopup_next").className=""),b=c.length;document.getElementById("imagepopup").style.display=
"block";document.getElementById("imagepopup_load").className="active";setTimeout(function(){document.getElementById("imagepopup").className="active"},30);b=new Image;b.onerror=function(){document.getElementById("imagepopup_load").className="";imagepopup.showtext("Loading errors","Failed to load the picture :(")};b.onload=function(){imagepopup.wherediv=e;document.getElementById("imagepopup_load").className="";document.getElementById("imagepopup_image"+g).className="";document.getElementById("imagepopup_image"+
e).className="active";document.getElementById("imagepopup_image"+e).innerHTML='<img id="nagy_kep'+e+'" src="'+a+'">';imagepopup.resizeimage();document.getElementById("imagepopup_panel").innerHTML='<a href="'+a+'" target="_blank">Link</a> <a href="javascript://" onclick="imagepopup.hideimage();" class="close">x</a>';document.getElementById("imagepopup_text").innerHTML=d;""!=f&&((new Image).src=f)};b.src=a},showtext:function(a,d){document.getElementById("imagepopup_fixer").style.display="none";document.getElementById("imagepopup").style.display=
"block";document.getElementById("imagepopup_image1").innerHTML='<div id="window"><h3 class="title">'+a+"</h3><p>"+d+"</p></div>";document.getElementById("imagepopup_panel").innerHTML='<a href="javascript://" onclick="imagepopup.hideimage();" class="close">x</a>';setTimeout(function(){document.getElementById("imagepopup").className="active";document.getElementById("imagepopup").className="active";document.getElementById("imagepopup_image1").className="active";document.getElementById("imagepopup_image2").className=
""},30)},next:function(){var a=document.getElementsByClassName(this.gallerye);this.showimage(void 0!=a[this.imageherei+1].dataset.bigsrc?a[this.imageherei+1].dataset.bigsrc:a[this.imageherei+1].src,a[this.imageherei+1].title,this.gallerye,this.imageherei)},prev:function(){var a=document.getElementsByClassName(this.gallerye);this.showimage(void 0!=a[this.imageherei-1].dataset.bigsrc?a[this.imageherei-1].dataset.bigsrc:a[this.imageherei-1].src,a[this.imageherei-1].title,this.gallerye,this.imageherei-
1)},hideimage2:function(a){"imagepopup"!=a.target.id&&"imagepopup_image1"!=a.target.id&&"imagepopup_image2"!=a.target.id||this.hideimage()},hideimage:function(){this.opened=!1;document.getElementById("imagepopup").className="";setTimeout(function(){document.getElementById("imagepopup").style.display="none";document.getElementById("imagepopup_text").innerHTML="";document.getElementById("imagepopup_image1").innerHTML="";document.getElementById("imagepopup_image2").innerHTML="";document.getElementById("imagepopup_prev").className=
"";document.getElementById("imagepopup_next").className="";document.getElementById("imagepopup_fixer").style.display="block"},400)},resizeimage:function(){if(document.getElementById("nagy_kep"+this.wherediv)){var a=document.getElementById("imagepopup").offsetWidth,d=document.getElementById("imagepopup").offsetHeight,d=d-50;document.getElementById("nagy_kep"+this.wherediv).style.maxWidth=a+"px";document.getElementById("nagy_kep"+this.wherediv).style.maxHeight=d+"px";var a=document.getElementById("nagy_kep"+
this.wherediv).offsetWidth,a=a-20,c=document.getElementById("nagy_kep"+this.wherediv).offsetHeight,d=(d-c)/2;6>d&&(d=4);document.getElementById("nagy_kep"+this.wherediv).style.marginTop=d+"px";600<a?(document.getElementById("imagepopup_text").style.width=a+"px",document.getElementById("imagepopup_text").className="kepben",d=c+d+5,document.getElementById("imagepopup_text").style.top=d+"px"):(document.getElementById("imagepopup_text").style.width="",document.getElementById("imagepopup_text").style.top=
"",document.getElementById("imagepopup_text").className="")}},keyboard_view:function(){window.addEventListener("keyup",function(a){imagepopup.opened&&(a="which"in a?a.which:a.keyCode,37==a&&imagepopup.hasprev?imagepopup.prev():39==a&&imagepopup.hasnext?imagepopup.next():27==a&&imagepopup.hideimage())})},mobiledrag:function(){function a(b,a){startx=b;starty=a;ennyit2=ennyit=0;starttop=document.getElementById("nagy_kep"+imagepopup.wherediv).style.marginTop;starttop=starttop.replace("px","")}function d(b,
a,d){ennyit=b-startx;ennyit2=starty-a;Math.abs(ennyit)>Math.abs(ennyit2)?document.getElementById("nagy_kep"+imagepopup.wherediv).style.marginLeft=ennyit+"px":(b=starttop-ennyit2,document.getElementById("nagy_kep"+imagepopup.wherediv).style.marginTop=b+"px");d.preventDefault()}function c(){var a="0px";Math.abs(ennyit)>Math.abs(ennyit2)?(120<ennyit&&imagepopup.hasprev?a="100%":-120>ennyit&&imagepopup.hasnext&&(a="-200%"),document.getElementById("nagy_kep"+imagepopup.wherediv).className="touch",document.getElementById("nagy_kep"+
imagepopup.wherediv).style.marginLeft=a,120<ennyit&&imagepopup.hasprev?imagepopup.prev():-120>ennyit&&imagepopup.hasnext&&imagepopup.next()):100<ennyit2||-100>ennyit2?imagepopup.hideimage():(a=starttop+"px",document.getElementById("nagy_kep"+imagepopup.wherediv).className="touch",document.getElementById("nagy_kep"+imagepopup.wherediv).style.marginTop=a);setTimeout(function(){document.getElementById("nagy_kep"+imagepopup.wherediv).className=""},200)}ennyit2=starttop=ennyit=starty=startx=0;window.PointerEvent&&
"undefined"==typeof document.documentElement.ontouchstart?navigator.maxTouchPoints&&1<navigator.maxTouchPoints&&(window.addEventListener("pointerdown",function(b){a(b.clientX,b.clientY)},!1),window.addEventListener("pointermove",function(a){d(a.clientX,a.clientY,a)},!1),window.addEventListener("pointerup",function(a){c()},!1)):(document.getElementById("imagepopup").addEventListener("touchstart",function(b){b=b.targetTouches[0];a(b.pageX,b.pageY)},!1),document.getElementById("imagepopup").addEventListener("touchmove",
function(a){var c=a.targetTouches[0];d(c.pageX,c.pageY,a)},!1),document.getElementById("imagepopup").addEventListener("touchend",function(a){c()},!1))},hideview:function(a){a=document.getElementById(a);a.style.opacity="1"==a.style.opacity?"0":"1"}};
